Vagrant.configure("2") do |config|
  config.vm.define "jenkins-server" do |server|
    server.vm.box = "ubuntu/bionic64"
    server.vm.network "forwarded_port", guest: 8080, host: 8080
    server.vm.network "private_network", ip: "192.168.56.10"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    server.vm.provision "file", source: "./provision/install_docker.sh", destination: "/home/vagrant/install_docker.sh"
    server.vm.provision "file", source: "./provision/install_jenkins_server.sh", destination: "/home/vagrant/install_jenkins_server.sh"
    server.vm.provision "shell", inline: "bash /home/vagrant/install_docker.sh"
    server.vm.provision "shell", inline: "bash /home/vagrant/install_jenkins_server.sh"
  end

  config.vm.define "jenkins-worker" do |worker|
    worker.vm.box = "ubuntu/bionic64"
    worker.vm.network "private_network", ip: "192.168.56.11"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    worker.vm.provision "file", source: "./provision/install_jenkins_worker.sh", destination: "/home/vagrant/install_jenkins_worker.sh"
    worker.vm.provision "shell", inline: "bash /home/vagrant/install_jenkins_worker.sh"
  end
end
