
Vagrant.configure("2") do |config|
  # Database VM (DB_VM)
  config.vm.define "db_vm" do |db|
    db.vm.box = "ubuntu/bionic64"
    db.env.enable
    db.vm.network "private_network", ip: "192.168.56.10"
    db.vm.hostname = "db.vm"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
    end
    db.vm.provision "shell", path: "db_provision.sh",
        env: { DB_USER: ENV['DB_USER'], DB_PASS: ENV['DB_PASS'], DB_NAME: ENV['DB_NAME'], DB_PORT: ENV['DB_PORT'] }
  end

   # Application VM (APP_VM)
  config.vm.define "app_vm" do |app|
    app.vm.box = "ubuntu/bionic64"
    app.env.enable
    app.vm.network "private_network", ip: "192.168.56.11"
    app.vm.hostname = "app.vm"

    # Port forwarding from APP_VM port 8080 to host port 8080
    app.vm.network "forwarded_port", guest: 8080, host: 8080
    app.vm.provider "virtualbox" do |vb|
     vb.memory = 2048
     vb.cpus = 2
    end
    app.vm.provision "shell", path: "app_provision.sh",
         env: { DB_USER: ENV['DB_USER'], DB_PASS: ENV['DB_PASS'], DB_NAME: ENV['DB_NAME'], DB_PORT: ENV['DB_PORT'], DB_HOST: '192.168.56.10' }
  end
end
